source 'https://git.wemomo.com/next/Specs.git'
source 'https://github.com/cosmos33/MMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JusticeCenterDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JusticeCenterDemo
  pod 'MMWebUploader', '1.0.5'
  pod 'CocoaAsyncSocket'
  
  pod 'MMJusticeCenter', :path => '../'

  target 'JusticeCenterDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JusticeCenterDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
